# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Phase 1 & 2 Combined: Train, Validate, AND Test BERT4Rec on IND data
# Input files: train_ind.inter, val_ind.inter, test_ind.inter
# Output:
#   - Saved model checkpoint based on best val_ind performance
#   - Console/Log output including metrics on test_ind.inter
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Basic settings
model: BERT4Rec
dataset: mind_large # Directory containing the .inter files
data_path: /home/aiscuser/

# --- Data Settings ---
# dataset config : Sequential Recommendation
load_col:
  inter: [user_id, item_id, timestamp]
  item: [item_id]
field_separator: "\t"
seq_separator: " "

USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id

MAX_ITEM_LIST_LENGTH: 100



TIME_FIELD: timestamp
# RATING_FIELD: rating # REMOVED - No rating column in the data/header

# Sequential Model Specific Settings
# Other BERT4Rec specific hyperparameters (Refer to RecBole docs for details and defaults)
hidden_size: 256
inner_size: 256
n_layers: 3
n_heads: 4
hidden_dropout_prob: 0.15
attn_dropout_prob: 0.15
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
mask_ratio: 0.2

# --- Training Settings ---
epochs: 10             # Maximum number of training epochs
train_batch_size: 8192   # Adjust based on GPU memory
learning_rate: 0.00002    # Starting learning rate (tune this)
stopping_step: 10       # Patience for early stopping
train_neg_sample_args: {'distribution': 'uniform', 'sample_num': 10, 'dynamic': false}
val_neg_sample_args: {'distribution': 'uniform', 'sample_num': 20, 'dynamic': false}
test_neg_sample_args: {'distribution': 'uniform', 'sample_num': 100, 'dynamic': false}
loss_type: BPR
# weight_decay: 0.0

# --- Evaluation Settings (Used for BOTH Validation and Final Test) ---
eval_args:
  group_by: user
  order: 'TO'
  split: {'LS': 'valid_and_test'}
  mode: full
eval_batch_size: 512
metrics: ['Recall', 'MRR', 'NDCG', 'Precision']
topk: [10, 20, 50, 100]
valid_metric: MRR@10
metric_decimal_place: 6


# --- Experiment Settings ---
reproducible: True
seed: 2025
device: cuda           # Use 'cuda' for GPU or 'cpu'

# --- Multi‑GPU Settings ---

dataloader_pin_memory: True
dataloader_temp_dir: "/scratch" 


worker: 0
gpu_id: "4,5,6,7"       
use_gpu: True

# Mixed precision
enable_amp: False
enable_scaler: True

# --- Logging Settings ---
log_level: DEBUG         # Set to DEBUG for more verbose logging
log_file: bert4rec_v2.log    # Saves logs to recbole.log file

# --- Checkpoint & Saving ---
save_best_model: True
# Save the best model based on validation performance
checkpoint_dir: /home/aiscuser/final_ckpts/ # Directory to save checkpoints, adjust as needed