# config.yaml

input_json: "splits/ood_test_users.json"
sqlite_db: "amazon_parquet_data/metadata_titles.db"
output_path: "long_horizon_experiments/gemma2-9b-test_full_long_horizon.jsonl"
is_ood: false

model:
  name: "google/gemma-2-9b-it"
  num_gpus: 4
  temperature: 0.7
  top_p: 0.8
  max_tokens: 350
