# config.yaml

input_json: "splits/ood_test_users.json"
sqlite_db: "amazon_parquet_data/metadata_titles.db"
output_path: "llm_experiments/gemma3_12b_test_full.jsonl"
is_ood: false

model:
  name: "google/gemma-2-9b-it"
  num_gpus: 8
  temperature: 0.7
  top_p: 0.8
  max_tokens: 220
